spring:
  datasource:
    url: jdbc:mysql://192.168.1.83:3306/flyway?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: liquido
    driver-class-name: com.mysql.cj.jdbc.Driver

#  # flyway 配置
  flyway:
    # 启用或禁用 flyway
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1


    #    # 字符编码 默认 UTF-8


#    clean-disabled: false
#    encoding: UTF-8
#    #    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
#    out-of-order: false
#    #    # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
#    #    # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
#    #    # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
#    schemas: flyway
#    #    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
#    validate-on-migrate: true
server:
  port: 8090



